version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    image: docker.io/bitnami/rails:7
    container_name: app_agenda
    ports:
      - '3001:3000'
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=app_development
    volumes:
      - './application:/app'
    depends_on:
      - mariadb
